global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@swayn-monitoring.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'
  routes:
  - match:
      alertname: Watchdog
    receiver: 'devnull'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'admin@swayn-monitoring.local'
    send_resolved: true

- name: 'devnull'
